### ISSUE TITLE
Extract function seems to extract to file

### ISSUE THREAD

**Issue by Gruntfuggly** [capaj/js-extractor#1]
I've been looking for something like this for a while - particularly just being able to extract to a local function.

The "extract function" from the packages menu (and context menu) seems to extract the function to a file though, and "extract function to file" from the packages menu doesn't seem to do anything?

Looks promising though!

**Comment by capaj** [comment]
@Gruntfuggly thanks for the interest, I should put in the readme that this is very early version. I have been working on extracting into a file first. Will add extracting into a function this evening hopefully

**Comment by capaj** [comment]
@Gruntfuggly I have implemented first version of extracting a raw function, you can try it out in 0.0.2, closing this issue, but if you have any other remarks or insights how to make it better, please open another issue
